---

- hosts: ubuntu
  connection: local
  tasks:
  - file: name={{ ansible_host }} state=directory
  - command: |
             debootstrap
               --variant=minbase
               --arch=amd64
               {{ CODENAME }}
               {{ ansible_host }}
               http://archive.ubuntu.com/ubuntu


- hosts: ubuntu
  connection: chroot
  tasks: 