---

- hosts: all
  connection: local
  tasks:
  - name: create dir {{ ansible_host }}
    file: name={{ ansible_host }} state=directory

- include: bootstrap_debian.yml
- include: bootstrap_ubuntu.yml
- include: setup_debian_ubuntu.yml
- include: bootstrap_alpine.yml
- include: setup_alpine.yml

- hosts: all
  connection: local
  tasks:
  - name: Packing rootfs
    command: tar --numeric-owner -czf work/{{ inventory_hostname }}/rootfs.tar.gz -C work/{{ inventory_hostname }} ./rootfs
  - copy: src=lxc-config.ubuntu dest={{ ansible_host }}/../lxc-config
  - template:
      src: metadata.json
      dest: "{{ ansible_host }}/../metadata.json"
  - name: Packing box
    command: tar -czf work/{{ inventory_hostname }}.box -C {{ ansible_host }}/../ rootfs.tar.gz lxc-config metadata.json
